#!/bin/bash

llfull() {
  # `ls` with some information and header
  
  gls -lAhF --time-style='+%Y-%m-%d %H:%M:%S %z' \
    | sed 1d \
    | awk -v OFS='\t' 'BEGIN {print "PERMISSION\tLINKS\tOWNER\tGROUP\tSIZE\tDATE\tHH:MM:SS\tTZ\tNAME\n";}
                       {s=""; for (i=9; i<=NF; i++) s=s$i" "; print $1,$2,$3,$4,$5,$6,$7,$8,s;}' \
    | column -t -s $'\t'
}

llpart() {
  # Similar to `llfull` but with less columns
  
  gls -lAhF --time-style='+%Y-%m-%d %H:%M:%S %z' \
    | sed 1d \
    | awk -v OFS='\t' 'BEGIN {print "SIZE\tDATE\tHH:MM:SS\tTZ\tNAME\n";}
                       {s=""; for (i=9; i<=NF; i++) s=s$i" "; print $5,$6,$7,$8,s;}' \
    | column -t -s $'\t'
}

file_time() {
  # Display file creation, modification, change and access times
  
  (printf 'CREATED\tMODIFIED\tCHANGED\tACCESSED\tSIZE\tNAME\n' \
     && stat -f '%SB%t%Sm%t%Sc%t%Sa%t%z%t%N' -t '%Y-%m-%d %H:%M:%S' *) \
    | column -t -s $'\t'
}

count_ext() {
  # Count the number of files with each extension
  # Ignore hidden files
  
  find . -maxdepth 1 -type f -not -path '*/\.*' \
    | sed -n 's/..*\.//p' \
    | sort | uniq -c \
    | awk 'BEGIN {print "EXTENSION\tCOUNT";} {print $2"\t"$1}' \
    | column -t -s $'\t'
}

ipynb_cleanmetadata() {
  # Clean all metadata from jupyter notebook files
  # 
  # Usage
  # -----
  # ipynb_cleanmetadata my-notebook.ipynb
  
  tmpfile=$(mktemp)
  jq --indent 1 '.cells[].metadata = {}' "$1" > ${tmpfile}
  mv ${tmpfile} "$1"
}
